-- MySQL Script generated by MySQL Workbench
-- Wed Jan 20 00:49:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`empresas` (
  `cnpj_emp` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(45) NULL,
  `endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`cnpj_emp`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ecommerce`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produtos` (
  `cod_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`cod_produto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ecommerce`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`fornecedores` (
  `cnpj_for` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(45) NULL,
  `endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`cnpj_for`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ecommerce`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`clientes` (
  `id_cli` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`id_cli`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ecommerce`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`categorias` (
  `cod_cate` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_cate`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ecommerce`.`empresas_has_Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`empresas_has_Produtos` (
  `cod_emp_prod` INT NOT NULL AUTO_INCREMENT,
  `empresas_cnpj_emp` INT NOT NULL,
  `Produtos_cod_produto` INT NOT NULL,
  `estoque` INT NULL,
  INDEX `fk_empresas_has_Produtos_Produtos1_idx` (`Produtos_cod_produto` ASC) VISIBLE,
  INDEX `fk_empresas_has_Produtos_empresas_idx` (`empresas_cnpj_emp` ASC) VISIBLE,
  PRIMARY KEY (`cod_emp_prod`),
  CONSTRAINT `fk_empresas_has_Produtos_empresas`
    FOREIGN KEY (`empresas_cnpj_emp`)
    REFERENCES `ecommerce`.`empresas` (`cnpj_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresas_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_cod_produto`)
    REFERENCES `ecommerce`.`Produtos` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ecommerce`.`Produtos_has_fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produtos_has_fornecedores` (
  `cod_pro_forne` INT NOT NULL AUTO_INCREMENT,
  `Produtos_cod_produto` INT NOT NULL,
  `fornecedores_cnpj_for` INT NOT NULL,
  PRIMARY KEY (`cod_pro_forne`),
  INDEX `fk_Produtos_has_fornecedores_fornecedores1_idx` (`fornecedores_cnpj_for` ASC) VISIBLE,
  INDEX `fk_Produtos_has_fornecedores_Produtos1_idx` (`Produtos_cod_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_has_fornecedores_Produtos1`
    FOREIGN KEY (`Produtos_cod_produto`)
    REFERENCES `ecommerce`.`Produtos` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_fornecedores_fornecedores1`
    FOREIGN KEY (`fornecedores_cnpj_for`)
    REFERENCES `ecommerce`.`fornecedores` (`cnpj_for`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ecommerce`.`Produtos_has_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produtos_has_categorias` (
  `cod_pro_cate` INT NOT NULL AUTO_INCREMENT,
  `Produtos_cod_produto` INT NOT NULL,
  `categorias_cod_cate` INT NOT NULL,
  INDEX `fk_Produtos_has_categorias_categorias1_idx` (`categorias_cod_cate` ASC) VISIBLE,
  INDEX `fk_Produtos_has_categorias_Produtos1_idx` (`Produtos_cod_produto` ASC) VISIBLE,
  PRIMARY KEY (`cod_pro_cate`),
  CONSTRAINT `fk_Produtos_has_categorias_Produtos1`
    FOREIGN KEY (`Produtos_cod_produto`)
    REFERENCES `ecommerce`.`Produtos` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_categorias_categorias1`
    FOREIGN KEY (`categorias_cod_cate`)
    REFERENCES `ecommerce`.`categorias` (`cod_cate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ecommerce`.`clientes_has_Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`clientes_has_Produtos` (
  `cod_cli_prod` INT NOT NULL AUTO_INCREMENT,
  `clientes_id_cli` INT NOT NULL,
  `Produtos_cod_produto` INT NOT NULL,
  `nota_fiscal` VARCHAR(45) NULL,
  `qt_comprada` INT NULL,
  PRIMARY KEY (`cod_cli_prod`),
  INDEX `fk_clientes_has_Produtos_Produtos1_idx` (`Produtos_cod_produto` ASC) VISIBLE,
  INDEX `fk_clientes_has_Produtos_clientes1_idx` (`clientes_id_cli` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_has_Produtos_clientes1`
    FOREIGN KEY (`clientes_id_cli`)
    REFERENCES `ecommerce`.`clientes` (`id_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_cod_produto`)
    REFERENCES `ecommerce`.`Produtos` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
